name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET for build
      uses: actions/setup-dotnet@v1
    - name: Setup .NET for GitVersion
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Run GitVersion
      run: |
        dotnet tool install --global GitVersion.Tool
        dotnet gitversion /output buildserver /nofetch
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c RELEASE
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c RELEASE -o ./out
